### ISSUE TITLE
some search filters not working in homer10 app (qxip-flow-plugin)

### ISSUE THREAD

**Issue by bilalrao12** [sipcapture/homer-docker#12]
Hi, I was testing this new plugin in homer10 and observing issues with some of the search filters

e.g If I want to search a specific call-id, I get No Data in result.

![image](https://github.com/sipcapture/homer-docker/assets/118199337/464d5383-9173-495d-904c-8509ed8927eb)

generated query for this:
{callid=~"ltk2n@127.0.0.1_b2b-1"} | regexp "To: <sip:(?<to_user>\w+)" | regexp "From: <sip:(?<from_user>\w+)" | regexp "To: <sip:.*@(?<to_domain>[a-zA-Z0-9.]+)" | regexp "From: <sip:.*@(?<from_domain>[a-zA-Z0-9.]+)" | regexp "Call-ID:\s+(?<callid>.+?)\r\n"

similar issue happens when searching for from_user, to_user, from_domain and to_domain.

**Comment by lmangani** [comment]
@bilalrao12 wrong repository 😄  this issue goes into https://github.com/metrico/grafana-flow
