### ISSUE TITLE
Running behind a specific IP address

### ISSUE THREAD

**Issue by televi** [sipcapture/homer-docker#13]
I needed to deploy the HOMER stack behind a single IP address (not 0.0.0.0) since it's on a server with other docker compose entities that also expose a web server.  I was able to get that to work and wanted to share what I did in case it's useful for other people (or in case there's a better way for me to have done that).

Would you prefer I simply provide what I did here (just updating some of the entries under the various port sections) or would a PR for an update to a readme or something be better?

**Comment by lmangani** [comment]
Thanks @televi the best way is to contribute to any of the project readmes or guides mentioning any such example. In the specific case of docker configuration, there are always infinite edge cases so we go for the most generic and leave the exercise up to the reader but it always helps to have more examples for sure.
