### ISSUE TITLE
call flow not data

### ISSUE THREAD

**Issue by manchelsi** [sipcapture/homer-docker#2]
<img width="1161" alt="Снимок экрана 2023-09-12 в 07 47 16" src="https://github.com/sipcapture/homer-docker/assets/15113513/afa9be7a-8bad-4c97-b071-62555cf9032c">

and systemd log:

```
root@homer:/usr/src/homer-docker/all-in-one# journalctl -f
Sep 12 04:49:17 homer systemd[1]: run-docker-runtime\x2drunc-moby-755007914bf62162540c5c0f2d4d4026e98b62ea12a9d9c08032f2a4cae8991c-runc.MDkHH5.mount: Deactivated successfully.
Sep 12 04:49:18 homer systemd[1]: run-docker-runtime\x2drunc-moby-755007914bf62162540c5c0f2d4d4026e98b62ea12a9d9c08032f2a4cae8991c-runc.dtqJ54.mount: Deactivated successfully.
Sep 12 04:49:19 homer systemd[1]: run-docker-runtime\x2drunc-moby-755007914bf62162540c5c0f2d4d4026e98b62ea12a9d9c08032f2a4cae8991c-runc.wLWYZw.mount: Deactivated successfully.
Sep 12 04:49:20 homer systemd[1]: run-docker-runtime\x2drunc-moby-755007914bf62162540c5c0f2d4d4026e98b62ea12a9d9c08032f2a4cae8991c-runc.TCNH3X.mount: Deactivated successfully.

```

container id 75500791:

```
root@homer:/usr/src/homer-docker/all-in-one# docker ps | grep 75500791
755007914bf6   clickhouse/clickhouse-server:22.8-alpine   "/entrypoint.sh"         10 minutes ago   Up 10 minutes (healthy)   0.0.0.0:8123->8123/tcp, :::8123->8123/tcp, 0.0.0.0:9000->9000/tcp, :::9000->9000/tcp, 9009/tcp                                                                  clickhouse-server
```

**Comment by lmangani** [comment]
@manchelsi You did not include any details or valuable information, we can't guess problems from screenshots. Your tables seemsempty.

**Comment by manchelsi** [comment]
![Screenshot_20230912_100909](https://github.com/sipcapture/homer-docker/assets/15113513/49f303f7-66c1-4e8c-8d50-88c661c04c4b)

Packages are generated by docker-hepgen. But call-flows are empty.

**Comment by lmangani** [comment]
These are statistics. Try to restart heplify-server and see if messages pop up, it might be due to a slow startup sequence.

**Comment by manchelsi** [comment]
`docker restart heplify-server
`
yes, now it works. Need a timeout for heplify-server

![Screenshot_20230912_105721](https://github.com/sipcapture/homer-docker/assets/15113513/b71945e7-9abd-4d7a-b9c8-0e227d72cb4d)

**Comment by lmangani** [comment]
Thanks for the confirmation. We'll push a fix for this common slow startup issue this week.

**Comment by lmangani** [comment]
Please pull the latest containers, the issue should be gone.
