### ISSUE TITLE
Stupid question about the web

### ISSUE THREAD

**Issue by SerhiiZahuba** [sipcapture/homer-docker#3]
I am trying to install version 10 through docker compose. Containers are all created without problems. The old port 9080 is missing here. On which port is the web now?

![image](https://github.com/sipcapture/homer-docker/assets/36307887/5df96405-d2e4-4f22-80e4-8358c42cadb2)

I've tried everything in the containers but it's empty. My OS is Centos 7.

I excluded the old version of homer (docker-compose down)

![image](https://github.com/sipcapture/homer-docker/assets/36307887/4f814988-1a5d-4f95-b48b-d3750cd99941)

**Comment by lmangani** [comment]
Hello @SerhiiZahuba this is not a stupid question since its about a radical change

> The old port 9080 is missing here. On which port is the web now?

The only UI is Grafana in HOMER 10

Note this is not yet a finished feature, but its rapidly evolving

**Comment by SerhiiZahuba** [comment]
Thanks

**Comment by airsay** [comment]
> Hello @SerhiiZahuba this is not a stupid question since its about a radical change
> 
> > The old port 9080 is missing here. On which port is the web now?
> 
> **The only UI is Grafana in HOMER 10**
> 
> Note this is not yet a finished feature, but its rapidly evolving

@lmangani would that be port 9030 (referencing HOMER 7 doc for that port). If yes, it doesn't work for me

**Comment by lmangani** [comment]
@airsay you need to use whatever port Grafana is mapped to, default is 3000

**Comment by airsay** [comment]
@lmangani thank you

**Comment by airsay** [comment]
@lmangani 
How do we send hep data to Homer 10?

**Comment by lmangani** [comment]
@airsay the same way as before using HEP to heplify-server which in turn writes to DB/qryn

**Comment by 2naive** [comment]
@lmangani homer7's table view was done so right - unfortunately don't see same usability in homer10/grafana :(

**Comment by lmangani** [comment]
@2naive you can still use it :) the grafana panel is not a replacement

**Comment by 2naive** [comment]
@lmangani was referring to this your post that confused:
> The only UI is Grafana in HOMER 10
As I also couldn't find web app in v10 yml 🤷‍♂️

**Comment by dhanh-ryuu** [comment]
can i use homer ui (not grafana UI) with homer v10? as i understand v10 architecture has changed to clickhouse which no longer uses sql so v7 UI cannot be used with v10

**Comment by lmangani** [comment]
> can i use homer ui (not grafana UI) with homer v10? as i understand v10 architecture has changed to clickhouse which no longer uses sql so v7 UI cannot be used with v10

No you cannot, and remember Homer 10 is an R&D release - Homer 11 brings the UI back and its currently in alpha. There's no Clickhouse either, so please do not consider even versions as references. Only odd versions are LTS
