### ISSUE TITLE
error in the template Grafana

### ISSUE THREAD

**Issue by SerhiiZahuba** [sipcapture/homer-docker#7]
Hello. Found an error in the template Grafana. In expr, need to remove a space at the end of the term.

https://github.com/sipcapture/homer-docker/blob/b62f58fdf34b00fee2cd3e38923aa121dcf1fdb9/all-in-one/grafana/provisioning/dashboards/CallFlow_Dashboard.json#L193

"expr": "{job=\"heplify-server\", src_ip=~\"$src_ip\", dst_ip=~\"$dst_ip\"} | response=~\"$method\" or type!=\"sip\" |~ `${search:raw}` | regexp \"Call-ID:\\s+(?<callid>.+?\r\n)\"",

needs replace to

"expr": "{job=\"heplify-server\", src_ip=~\"$src_ip\", dst_ip=~\"$dst_ip\"} | response=~\"$method\" or type!=\"sip\" |~ `${search:raw}` | regexp \"Call-ID:\\s+(?<callid>.+?)\"",

**Comment by tony1661** [comment]
I believe I have this covered in a [PR](https://github.com/sipcapture/homer-docker/pull/8)

**Comment by lmangani** [comment]
Fixed by @tony1661
